// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID     pgtype.UUID `db:"id"`
	UserID pgtype.UUID `db:"user_id"`
	Name   string      `db:"name"`
}

type User struct {
	ID   pgtype.UUID `db:"id"`
	Name string      `db:"name"`
}
